#!/bin/bash

. $dracutfunctions

inst "$moddir/lib/chroot-lib.sh" /lib/osr/

# What do we need for mounting the chroot
inst_hook netroot    11 "$moddir/osr-detect-chroot.sh"
inst_hook netroot    50 "$moddir/osr-mount-chroot.sh"
inst_hook pre-pivot  51 "$moddir/osr-move-chroot.sh"